version: '3.9'

services:
  db:
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lenslocked
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: no
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080